# Use root/example as user/password credentials
version: "3.7"

services:
    nginx:
        build:
            dockerfile: ./Nginx/Dockerfile
            context: .
        image: nginx
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80
        depends_on:
            - ui
            - api
    
    ui:
        build: ./sosnazario-ui
        env_file: ./.env
        restart: unless-stopped
        stop_signal: SIGINT
        ports:
            - 8000:80

    api:
        build: ./sosnazario-api
        restart: on-failure
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        depends_on:
            - postgresdb
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$POSTGRESDB_DATABASE",
                "spring.datasource.username" : "$POSTGRESDB_USER",
                "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
                "spring.jpa.hibernate.ddl-auto" : "update"
            }'
        volumes:
            - ./Temp/.m2:/root/.m2
        stdin_open: true
        tty: true

    postgresdb:
        image: postgres
        restart: unless-stopped
        env_file: ./.env
        environment:
            - POSTGRES_USER=$POSTGRESDB_USER
            - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
            - POSTGRES_DB=$POSTGRESDB_DATABASE
        ports:
            - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
        volumes:
            - ./Temp/postgres-data:/var/lib/postgresql/data

    # pgadmin:
    #     # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    #     image: dpage/pgadmin4
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
    #         PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    #         PGADMIN_LISTEN_PORT: $PGADMIN_LISTEN_PORT
    #     ports:
    #         - 16543:$PGADMIN_LISTEN_PORT
    #     depends_on:
    #         - postgresdb
    #     volumes:
    #         - ./Temp/pgadmin:/var/lib/pgadmin